/*
 * Ent Schema API
 *
 * This is an auto generated API description made out of an Ent schema definition
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateCardRequest {
    #[serde(rename = "card", skip_serializing_if = "Option::is_none")]
    pub card: Option<i32>,
    #[serde(rename = "skill", skip_serializing_if = "Option::is_none")]
    pub skill: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    #[serde(rename = "cp", skip_serializing_if = "Option::is_none")]
    pub cp: Option<i32>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    #[serde(rename = "author", skip_serializing_if = "Option::is_none")]
    pub author: Option<String>,
    #[serde(rename = "owner", skip_serializing_if = "Option::is_none")]
    pub owner: Option<i32>,
}

impl UpdateCardRequest {
    pub fn new() -> UpdateCardRequest {
        UpdateCardRequest {
            card: None,
            skill: None,
            status: None,
            token: None,
            cp: None,
            url: None,
            count: None,
            author: None,
            owner: None,
        }
    }
}

