// Code generated by ogen, DO NOT EDIT.
package ogent

type CreateCardRes interface {
	createCardRes()
}

type CreateGroupRes interface {
	createGroupRes()
}

type CreateUeRes interface {
	createUeRes()
}

type CreateUserRes interface {
	createUserRes()
}

type DeleteCardRes interface {
	deleteCardRes()
}

type DeleteGroupRes interface {
	deleteGroupRes()
}

type DeleteUeRes interface {
	deleteUeRes()
}

type DeleteUserRes interface {
	deleteUserRes()
}

type ListCardRes interface {
	listCardRes()
}

type ListGroupRes interface {
	listGroupRes()
}

type ListGroupUsersRes interface {
	listGroupUsersRes()
}

type ListUeRes interface {
	listUeRes()
}

type ListUserCardRes interface {
	listUserCardRes()
}

type ListUserRes interface {
	listUserRes()
}

type ListUserUeRes interface {
	listUserUeRes()
}

type ReadCardOwnerRes interface {
	readCardOwnerRes()
}

type ReadCardRes interface {
	readCardRes()
}

type ReadGroupRes interface {
	readGroupRes()
}

type ReadUeOwnerRes interface {
	readUeOwnerRes()
}

type ReadUeRes interface {
	readUeRes()
}

type ReadUserRes interface {
	readUserRes()
}

type UpdateCardRes interface {
	updateCardRes()
}

type UpdateGroupRes interface {
	updateGroupRes()
}

type UpdateUeRes interface {
	updateUeRes()
}

type UpdateUserRes interface {
	updateUserRes()
}
